# Generated by Django 3.2 on 2021-08-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0002_remove_category_descriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
